######################
# Dockerfile for Client-Side Component (vote-client)
######################
FROM node:18-slim

WORKDIR /app

# Copy client app source files
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

# Expose the port
EXPOSE 3000

# Run the client
CMD ["npm", "start"]
