######################
# Kubernetes Manifest (vote-app.yaml)
######################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-server
  template:
    metadata:
      labels:
        app: vote-server
    spec:
      containers:
      - name: vote-server
        image: abtagir/vote-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-client
  template:
    metadata:
      labels:
        app: vote-client
    spec:
      containers:
      - name: vote-client
        image: abtagir/vote-client:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vote-server
spec:
  type: ClusterIP
  selector:
    app: vote-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vote-client
spec:
  type: NodePort
  selector:
    app: vote-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
